Dashboard backend
SkyndalexProjects/Skyndalex pull request #16
Opened 2023-03-24 20:59 UTC by KorrumzPL

Added:

1. Discord login and user data in JSON `(https://api.skyndalex.xyz/auth/dashboard/discord/data)`

2023-03-24 21:54 UTC, oceaann requested changes

2023-03-24 21:54 UTC, oceaann commented on src/routers/dashboard/discordAuth.js
> +const { secret, clientID, callbackURL } = require("../../config.json").discord
`secret` powinien być przechowywany w zmiennej środowiskowej a nie w pliku json

2023-03-24 22:01 UTC, livelove1987 requested changes

2023-03-24 22:27 UTC, oceaann requested changes

2023-03-24 22:27 UTC, oceaann commented on src/routers/dashboard/discordAuth.js
> +router.get('/callback', async (req, res) => {
To jest zapytanie do api wykonywane w kodzie czy bezpośrednio przez przeglądarkę otwierając stronę? Opowiedzi nie są przystosowane do jakiegokolwiek wyświetlania użytkownikowi, ale z jakiegoś powodu odpowiedzią jest redirect.

2023-03-24 22:27 UTC, oceaann commented on src/routers/app.js
> +    app.use("/auth/dashboard/discord", require("./dashboard/discordAuth.js"))
Ogólnie o wiele lepszym pomysłem by było czytelniejsze wyeksportowanie router w tym pliku, a importowanie go w `./dashboard/discordAuth.js`

2023-03-24 22:27 UTC, oceaann commented on src/routers/dashboard/discordAuth.js
> +            authorization: `Basic ${btoa(`${clientID}:${secret}`)}`,
```suggestion
    params.set('grant_type', 'authorization_code')
    params.set('code', req.query.code)
    params.set('redirect_uri', `https://api.skyndalex.xyz/auth/dashboard/discord/callback`)
    params.set('client_secret', secret)

    const response = await fetch('https://discord.com/api/oauth2/token', {
        method: 'POST',
        body: params.toString(),
        headers: {
```
Dokumentacja twierdzi, że secret tutaj powinien być podany w body, a nie w headerze [Dokumentacja discorda](https://discord.com/developers/docs/topics/oauth2#authorization-code-grant-redirect-url-example)

2023-03-24 22:36 UTC, oceaann commented
Fajnie by bylo jakby jeszcze nazwa pr'a mówiła o tym co on zmienia

2023-03-25 16:58 UTC, KorrumzPL commented
ok

2023-03-25 17:45 UTC, hackerytofficial commented
Good!

2023-03-26 11:25 UTC, oceaann commented
> Good!

?

2023-03-26 12:39 UTC, closed without merging