(rewrite): event and command handling
SkyndalexProjects/Skyndalex pull request #18
Opened 2023-03-27 20:11 UTC by KorrumzPL

To do:
 - [x] Slash command name parsing
 - [x] Slash command options parsing + validation
 - [x] Commands registration
 - [x] Events handling
-  [ ] Perm system

Command declaration:
```js
export default {
  names: ["add-money"],
  options: {
    user: {
      type: ApplicationCommandOptionType.User,
      description: "User to add money",
      compute: (option) => {
        if (!option.member)
          throw new Error(`${option.user.tag} is not on the server`);
        return option.member;
      },
      required: true,
    },
    amount: {
      type: ApplicationCommandOptionType.Integer,
      description: "Money amount",
      minValue: 1,
      maxValue: 2000,
      compute: (option) => {
        return option.value * 10;
      },
      required: true,
    },
  },
  description: "Test",
  run: async (client, interaction, options) => {
    
  },
};
```

`compute` usage: (first argument is [discord.js CommandInteractionOption](https://discord.js.org/#/docs/discord.js/main/typedef/CommandInteractionOption), the returned value is accessible by `options.get(option.name)` in the `run` function)
```js
compute: (option) => {
  if (!option.member)
    throw new Error(`${option.user.tag} is not on the server`);
  return option.member;
}
```

To declare a subcommand you need to add to names combined name of a command, subcommand group, and subcommand name (for example `names: ["case list"]`)

Example event declaration:
```js
export default async function (client) {
  console.log("Event received")
}
```

2023-03-28 14:26 UTC, hackerytofficial commented
Dobrze

2023-04-01 18:03 UTC, oceaann commented
![image](https://user-images.githubusercontent.com/47253870/229307136-c8e2af14-4bf6-4ed0-8739-8ff3b879eacc.png)
Polecam wyłączyć przed robieniem code-review

2023-04-02 08:39 UTC, oceaann requested changes

2023-04-02 08:39 UTC, oceaann commented on src/handlers/eventHandler.js
> +  const eventFiles = (await readdir("./events")).filter((file) =>
Ścierzka `./events` będzie prawidłowa tylko gdy uruchomi się kod za pomocą `node index.js` w katalogu src, jak się uruchomi kod za pomocą `node src/index.js` to nie będzie działać

2023-04-02 08:39 UTC, oceaann commented on src/utils.js
> +          { description, required, type, minLength, maxLength },
Brakujące opcje, na których ustawienia pozwala discord.js [(dokumentacja)](https://discord.js.org/#/docs/discord.js/main/typedef/ApplicationCommandOption), np. `maxValue`, `choices`

2023-04-02 08:39 UTC, oceaann commented on src/utils.js
> +    return {
Brakujące pole `defaultMemberPermissions` oraz kilka innych związanych z tłumaczeniem [(dokumentacja)](https://discord.js.org/#/docs/discord.js/main/class/ApplicationCommand)

2023-04-02 08:39 UTC, oceaann commented on src/handlers/eventHandler.js
> +  const eventFiles = (await readdir("./events")).filter((file) =>
Załadować dane z plików mozna tylko raz, a po uruchomieniu funkcji je rejestrować (by jak będzie więcej niż jeden client to nie powtażać tego)

2023-04-02 08:39 UTC, oceaann commented on package.json
> +  "main": "index.js",
Czemu `index.js` zamiast `src/index.js`?

2023-04-02 09:17 UTC, hackerytofficial commented on src/handlers/eventHandler.js
> +  const eventFiles = (await readdir("./events")).filter((file) =>
Ok

2023-04-02 10:13 UTC, livelove1987 commented on src/events/ready.js
> +  await client.rest.put(Routes.applicationCommands(client.user.id), {
Dodać opcje rejstrowania komend per guild ( w przypadku testowania )

2023-04-02 13:59 UTC, KorrumzPL commented on src/handlers/eventHandler.js
> +  const eventFiles = (await readdir("./events")).filter((file) =>
proszę o sprecyzowanie

2023-04-02 14:05 UTC, oceaann commented on src/handlers/eventHandler.js
> +  const eventFiles = (await readdir("./events")).filter((file) =>
`readdir` oraz `import` są wykonywane po każdym wykonaniu funkcji. W przypadku kiedy potrzebujemy uruchomić tą funkcję dla więcej niż jednego clienta będziemy poświęcać czas i zasoby serwera na załadowywanie tych samych danych po raz kolejny.

2023-04-02 19:48 UTC, oceaann commented on src/handlers/eventHandler.js
> +  const eventFiles = (await readdir("./events")).filter((file) =>
dalej nie naprawione

2023-04-03 18:46 UTC, KorrumzPL commented on src/handlers/eventHandler.js
> +  const eventFiles = (await readdir("./events")).filter((file) =>
> dalej nie naprawione

kiedy będę wprowadzał customboty po rewrite to wtedy naprawię

2023-04-03 18:46 UTC, KorrumzPL commented on src/handlers/eventHandler.js
> +  const eventFiles = (await readdir("./events")).filter((file) =>
tzn podczas rewrite

> > dalej nie naprawione
> 
> kiedy będę wprowadzał customboty po rewrite to wtedy naprawię

tzn podczas rewrite

2023-04-04 20:19 UTC, oceaann commented on src/handlers/eventHandler.js
> +  const eventFiles = (await readdir("./events")).filter((file) =>
Jesteś pewien, że odpowiadałeś na to co chciałeś? Nie wiem jak to ma być związane z custombotami.

2023-04-04 20:19 UTC, KorrumzPL commented on src/handlers/eventHandler.js
> +  const eventFiles = (await readdir("./events")).filter((file) =>
> Jesteś pewien, że odpowiadałeś na to co chciałeś? Nie wiem jak to ma być związane z custombotami.

hmmmm

2023-04-04 20:20 UTC, KorrumzPL commented on src/handlers/eventHandler.js
> +  const eventFiles = (await readdir("./events")).filter((file) =>
naprawię jutro, jutro też dodam handler do interakcji działający

2023-04-05 20:55 UTC, oceaann requested changes
W plikach `eventsHandler.js` i `commandsHandler.js` powtarzamy nazwę handlers mimo tego, że obydwa te pliki są w katalogu handlers. Nie rozumime czemu nie można by było tych plików nazwać `events.js` i `commands.js` (`/src/handlers/events.js`, `/src/handlers/commands.js`)

2023-04-11 09:18 UTC, oceaann requested changes

2023-04-11 09:18 UTC, oceaann commented on src/events/interactionCreate.js
> +  if (interaction.isCommand()) await onCommandInteraction(client, interaction);
```suggestion
  if (interaction.isCommand()) return await onCommandInteraction(client, interaction);
```

2023-04-11 09:18 UTC, oceaann commented on src/events/interactionCreate.js
> +        new ThrowMessage(client, interaction, error);
co ten "error handling" ma na celu xD

2023-04-11 09:18 UTC, oceaann commented on src/events/interactionCreate.js
> +  const embedNotFound = new EmbedBuilder()
deklarowanie zmiennej z embedem za każdym razem gdy dostajesz event `interactionCreate`, nawet gdy z tego nie korzystasz

2023-06-04 20:04 UTC, merged