Economy
SkyndalexProjects/Skyndalex pull request #4
Opened 2023-11-21 19:41 UTC by KorrumzPL

**These are just preliminary ideas, this pull request will be developed in the future.**

Commands:

Earning:

/work 
/slut
/crime

Other:

/daily 
/leaderboard

Account management:

/bal
/with
/dep

2023-11-23 07:28 UTC, banocean commented on src/index.js
How are those changes in scope of this pr?

2023-11-23 08:49 UTC, KorrumzPL commented on src/index.js
What do you mean? In the `.env` file, I only added the topgg webhook token, which doesn't affect the bot's running anyway

2023-11-23 20:59 UTC, banocean commented on src/index.js
I don't see how is the top.gg webhook stuff related to economy that is claimed to be scope of this pr in the title and description of it

2023-11-23 21:19 UTC, KorrumzPL commented on src/index.js
It does not have to be related

> I don't see how is the top.gg webhook stuff related to economy that is claimed to be scope of this pr in the title and description of it

2023-11-23 21:38 UTC, banocean commented on src/index.js
Isn't whole point of version control to keep track where and what was changed? Changes not related to things they are assigned to shouldn't be here imo

2023-11-23 22:07 UTC, KorrumzPL commented on src/index.js
Most of the time I try to keep version control track, but the integration of topgg may be related to this branch. For example, I can add a feature that gives rewards to the user in the economy for topgg vote. The description I have given is written only indicative go for sure many things will change (such as this) and I will keep it updated

2023-11-24 14:22 UTC, banocean commented on src/index.js
- if this feature will be in use for stuff not exclusive to the economy module it would make sens to put it in the separate branch (and pr)
- description doesn't mention anything like that for some reason

2023-11-24 14:23 UTC, banocean commented on src/index.js
Also please mark this pr as draft to avoid confusion regarding state of this pr

2023-11-24 15:35 UTC, KorrumzPL commented on src/index.js
Okay. I changed the description and marked pr as draft

2023-11-28 21:44 UTC, banocean requested changes

2023-11-28 21:44 UTC, banocean commented on README.md
> +- [ ] Version: `v1.1.1`
Jump from `1.0.0` to `1.1.1`? (not 1.1 or 1.0.1)

2023-11-28 21:44 UTC, banocean commented on src/.prettierignore
I think this file should be in `.gitignore`

2023-11-28 21:44 UTC, banocean commented on src/commands/bot/ping.js
> -    const confirm = new ButtonBuilder()
wtf? (also it's ping.js)

2023-11-28 21:44 UTC, banocean commented on src/commands/economy/bal.js
Is there any naming convention for files in this project?

2023-11-28 21:44 UTC, banocean commented on src/commands/economy/bal.js
> +      return interaction.reply({
Showing empty account balance would be better for ux

2023-11-28 21:44 UTC, banocean commented on src/commands/economy/bal.js
> +          value: `${BigInt(table?.wallet || 0).toLocaleString("en")}`,
- What's the point of converting it to bigint here?
- Optional chaining seems useless here considering [line 22](https://github.com/SkyndalexProjects/Skyndalex/pull/4/files#diff-beeae6a1fd8b6d20358b43920a128cc189658407dc326a469622b62260d60335R22)

2023-11-28 21:44 UTC, banocean commented on src/commands/economy/work.js
> +        wallet: (parseInt(table?.wallet || "0") + money).toString(),
`parseInt(null)` and `parseInt(undefined)` returns `NaN` so it would be better to allocate less memory
```suggestion
        wallet: (parseInt(table?.wallet) || 0 + money).toString(),
```

2023-11-28 21:44 UTC, banocean commented on src/prisma/schema.prisma
> +  jobJoined Boolean?
```suggestion
  hasJob Boolean?
```
https://dev.to/michi/tips-on-naming-boolean-variables-cleaner-code-35ig

2023-11-28 21:44 UTC, banocean commented on src/index.js
> +      .get("1058882286210261073")
Constant with this ID and name explaining it purpose sounds like a good idea

2023-11-28 21:44 UTC, banocean commented on .env.example
> +SUPPORT_SERVER_ID="SUPPORT_SERVER_ID"
Camle case in `CLIENT_ID` value, just to use capitalized sneak case in `SUPPORT_SERVER_ID`?

2023-11-28 21:44 UTC, banocean commented on package.json
> +    "prettier-plugin-organize-imports": "^3.2.4",
this should be in `devDependencies`
https://docs.npmjs.com/specifying-dependencies-and-devdependencies-in-a-package-json-file

2023-11-30 09:52 UTC, KorrumzPL commented on src/commands/bot/ping.js
> -    const confirm = new ButtonBuilder()
That's test stuff. I will remove it

2023-11-30 09:53 UTC, KorrumzPL commented on src/commands/economy/bal.js
not really

2023-11-30 09:54 UTC, KorrumzPL commented on src/commands/bot/ping.js
> -    const confirm = new ButtonBuilder()
I removed it*

2023-11-30 17:39 UTC, KorrumzPL commented on src/.prettierignore
Good idea

2023-11-30 17:39 UTC, KorrumzPL commented on src/commands/economy/bal.js
> +      return interaction.reply({
Good idea

2023-11-30 17:40 UTC, KorrumzPL commented on src/commands/economy/work.js
> +        wallet: (parseInt(table?.wallet || "0") + money).toString(),
I'll think about that

2023-11-30 20:51 UTC, MinerPL commented on src/.prettierignore
Worst idea, files with a list of ignored files should never be put into `.gitignore`

2023-12-01 06:18 UTC, banocean commented on src/.prettierignore
> Worst idea, files with a list of ignored files should never be put into `.gitignore`

Generally yes, but I think this file is there cuz @KorrumzPL opened src folder as the main one lol

2023-12-01 12:15 UTC, banocean commented on src/commands/economy/work.js
> +        wallet: (parseInt(table?.wallet || "0") + money).toString(),
> I'll think about that

There is nothing to think about, its just more performent approach that works the same (as I explained earlier)

2024-02-03 10:12 UTC, banocean reviewed
Haven't read even half of it yet

2024-02-03 10:12 UTC, banocean commented on .env.example
What's the point of removing those files? It's not a scope of this pr neither explained anywhere

2024-02-03 10:12 UTC, banocean commented on package-lock.json
Shouldn't this file be a part of gitignore?

2024-02-03 10:12 UTC, banocean commented on src/commands/bot/updates.js
> +          `Announcement ${page + 1} of ${items.length} by ${msgs.author}`,
Incorrect naming, page represents index and page should be equal to index + 1

2024-02-03 10:12 UTC, banocean commented on src/commands/dev/whitelist.js
> +      }`,
What the hell does unwhitelisted mean

2024-02-03 10:12 UTC, banocean commented on src/commands/economy/bal.js
> +    const wallet = table.wallet !== null ? BigInt(table.wallet) : BigInt(0);
```suggestion
    const wallet = BigInt(table.wallet || 0) ;
```

2024-02-03 10:12 UTC, banocean commented on src/commands/economy/bal.js
> +    const bank = table.bank !== null ? BigInt(table.bank) : BigInt(0);
Same as previous comment

2024-02-03 10:12 UTC, banocean commented on src/commands/economy/slut.js
> +        update: { wallet: (parseInt(user?.wallet || "0") + amount).toString() },
```suggestion
        update: { wallet: (parseInt(user?.wallet) || 0 + amount).toString() },
```

2024-02-03 10:12 UTC, banocean commented on src/commands/economy/text.js
> +      switch (interaction.options.getSubcommand()) {
A lot of repeated in this switch statement code ngl

2024-02-03 10:12 UTC, banocean commented on src/commands/economy/text.js
> +        content: `Operation failed. Check your arguments.`,
"your arguments"

2024-10-06 15:00 UTC, closed without merging